### ISSUE TITLE
Implement computation of residuals

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#119]
Add a mode to montblanc whereby residuals, the weighted difference between observed and model visibilities are output, rather than model visibilities.

**Initial post:** Currently, the weight vector is not applied to model visibilities before they are stored in global GPU memory, but instead to the delta of the model and observed visibilities. This should be changed so that the final model visibilities are weighted.

/cc  @bennahugo

**Comment by jtlz2** [comment]
@sjperkins @bennahugo Under what circumstances would you want weighted model (presumably for export) visibilities as opposed to unweighted..?

**Comment by sjperkins** [comment]
@jtlz2 /cc @bennahugo @o-smirnov  After further discussions with Ben, we've decided that the requirements here are a new mode in montblanc whereby the weighted difference of the model and observed visibilities (residuals) is stored in the model visibilities.

This shouldn't be difficult to implement. However, I am keen to differentiate between the different modes in which montblanc is used. I see three use cases at present:

1. Chi-squared calculator
2. Residual calculator
3. Visibility predict

I'm keen to disable arrays unrelated to different use cases as it creates less ambiguity for the user. So for e.g. predict, removed observed visibilities, weight vector and flagging. And in the case of residual calculator, change `model_vis` to `residuals` for instance.

**Comment by jtlz2** [comment]
@sjperkins Got it now - sounds excellent!

**Comment by o-smirnov** [comment]
I'm a bit confused about this to be honest -- can you fill me in on Monday?

**Comment by sjperkins** [comment]
Sure, wasn't intending to do this straight away and I wanted to discuss the above use cases with you in person.

**Comment by sjperkins** [comment]
Implemented in #131
