### ISSUE TITLE
Does the expression for spectral intensity apply to the entire brightness matrix or only to I?

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#120]
Currently, the expression for the spectral intensity is multiplied into the entire brightness matrix like so:

![image](http://quicklatex.com/cache3/86/ql_839fc3433b50708845534f64a5e9a686_l3.png)

Landman suggested that that spectral intensity only applies to I. It seems to me that the above is valid iff `I^2 == Q^2 + U^2 + V^2`. @o-smirnov, @jtlz2  could you provide input here?

**Comment by sjperkins** [comment]
This comment intentionally left blank

**Comment by twillis449** [comment]
To a zeroth order approximation you are more or less correct. The polarized signal can never be more that I, so if e.g. I is decreasing toward increasing frequency then so must the polarized components. However, due to various physical processes both internal to the sources and along the path between the source and the telescope, the polarized component of the signal (or percentage polarization) will tend to increase as the frequency increases. The exact behaviour varies from source to source. There is no hard and fast answer. But if not a lot is known about the source, your current operation is as good as anything else.

**Comment by sjperkins** [comment]
@SpheMakh  makes the point that the quantities involved in I (intensity) are different from Q, U and V (rotational). It seems that the spectral intensity should only be applied to I if possible.

Thankfully this change is not difficult to make.

**Comment by jtlz2** [comment]
@sjperkins If you have no spectral-index term for Q, U and V, you are making the (dangerous) assumption that all sources ever have flat (alpha=1) spectra, and independently of what I is doing, which seems implausibly unlikely.

So a more sensible (and flexible) approach to adopt for now might be to allow one alpha per stokes parameter.

I don't think we ever talked about allowing for higher-order dependencies. If you are looking to generalize, you could allow for alpha to be an array over frequency that could then be populated by the user (cf. weight_vector).

**Comment by sjperkins** [comment]
An alpha per stokes parameter is also an easy change.

**Comment by o-smirnov** [comment]
I don't believe alpha per Stokes parameter is useful or physical. If you're in the mood for coding, the next useful change is to implement rotation measure (RM): 

phi = RM*(lambda / lambda_0)^2
Q = cos(phi)*Q_0 - sin(phi)*U_0
U = sin(phi)*Q_0 + cos(phi)*U_0

(can anybody remind me how to render math here?)

...and multiply the brightness matrix overall by the spectral index scaling law.

**Comment by sjperkins** [comment]
@o-smirnov quicklatex will render latex maths into a png

**Comment by o-smirnov** [comment]
OK sorry that should be

![image](https://cloud.githubusercontent.com/assets/6470079/15211430/6bf9217a-183b-11e6-9e7d-20e50870c256.png)

...and QU rotate through twice the angle. Damn, can't get it to render matrices right!

**Comment by sjperkins** [comment]
@o-smirnov Cool! Lets discuss more when you're back, this isn't urgent.

**Comment by sjperkins** [comment]
#121 confirms Meqtrees and Montblanc produce same results w.r.t. IQUV and spi.

**Comment by sjperkins** [comment]
Closing this in favour of https://github.com/ska-sa/montblanc/issues/171, which contains further discussion on expanded spectral intensity expression.
