### ISSUE TITLE
Take parallactic angle per timestep from MeasurementSet

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#141]
Presently in the Beam, we have a single scalar parallactic angle that is set by the user. This must be changed to a parallactic angle per timestep, derived from the MeasurementSet.

Parallactic angle computation in Chapter 19 of Synthesis Imaging II

http://www.gb.nrao.edu/GBT/DA/gbtidl/release2pt9/contrib/contrib/parangle.pro

**Comment by bennahugo** [comment]
Comments from discussion

- Use  parallactic angle in Ch19 of Synthesis Imaging II
- l set to delta
- m set to -H?
- Phi set to each antenna's latitude.
  1. New array, **antenna_position** in latitude, longitude and altitude of shape (na, 3), dtype 'ft'
  2. This is a strange earth coordinate system, that we'll need to change with casameasures.
  2. Modify loaders to extract these coordinates from the antenna table.
  3. Modify CPU Solver and GPU RimeEBeam kernel to use this new array

**Comment by twillis449** [comment]
You don't need CASA measures (although I admit it would be a good check on the appended code)

# Convert latitude (radians), longitude (radians) and elevation (metres) to ITRF XYZ
def WGS84ToITRF(lat, lon, h): # WGS-84 to ITRF
        sm_a = 6378137.0
        invf = 298.257223563
        f = 1.0 / invf
        SINK = math.sin(lat)
        COSK = math.cos(lat)
        e2 = 2.0 * f - f * f
        v = sm_a / math.sqrt(1.0 - e2 * SINK * SINK)
        x = (v + h) * COSK * math.cos(lon)
        y = (v + h) * COSK * math.sin(lon)
        z = ((1 - e2) * v + h) * SINK
        return x, y, z

**Comment by sjperkins** [comment]
@twillis449 That looks goo. However, we need to go from ITRF to (I think) WGS84. Do you have an inverse for the above?

**Comment by jtlz2** [comment]
@sjperkins I know a good book :) [www.cambridge.org/practicalastronomy](www.cambridge.org/practicalastronomy)

**Comment by sjperkins** [comment]
@jtlz2 Need the GBP to fall a bit more relative to the ZAR.  Can you liase with Boris?

**Comment by jtlz2** [comment]
@sjperkins There is a copy somewhere at SKA (Foley?). \#borisforpm

**Comment by twillis449** [comment]
Here's the python code to go in either direction.

[coordinates.txt](https://github.com/ska-sa/montblanc/files/337163/coordinates.txt)

**Comment by bennahugo** [comment]
@twillis449 Thanks these will be very helpful!

**Comment by sjperkins** [comment]
getBeamSampleTimes

**Comment by sjperkins** [comment]
Implemented for a single reference antenna in #146 . Leaving this open as we'll support parallactic angles for each antenna at each timestep in future.

**Comment by sjperkins** [comment]
Note to self, this is implemented in the tensorflow version, this issue can be closed when its merged into master.

**Comment by sjperkins** [comment]
Implemented in #185
