### ISSUE TITLE
E beam cubes and multiple bands

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#142]
Currently, Montblanc stacks multiple bands ontop of each other in the channel dimension. Thinking about it, there is a probably a bug here in how the beam cube handles multiple bands. Currently:
1. The position in the global channel space is scaled to a position within the cube.
2. The two adjacent voxels in the cube's frequency dimension are interpolated.

@o-smirnov I imagine this interpolation will probably be incorrect if the global channel position lies on the boundary of two bands. If so, how should we handle this?
1. A beam cube per band?

**Comment by o-smirnov** [comment]
I don't quite follow -- you'll need to draw me a picture or something...

**Comment by sjperkins** [comment]
@o-smirnov See the following image:

![image](https://cloud.githubusercontent.com/assets/3530212/16271336/df119e7a-3899-11e6-8f0b-10c71e0f6bbb.jpg)

Since I'm now stacking each band on top of each other in the channel dimension, I'm wondering how to properly map from 16k (for e.g.) channels with 3 bands of 5400 channels to a single voxel cube with 50 channel images of size (l,m).

I'd imagine there's going to be some discontinuity at the the start/end of each band and this will also need to be represented in the cube. Simplest in my mind is to have a cube per band? We can discuss more in person next week.

**Comment by o-smirnov** [comment]
There's not necessarily a discontinuity, but it's best not to assume anything. In particular, our real beam cubes do not always have a regularly-sampled frequency axis in the first place! So you must store a vector of "beam frequencies", and interpolate each channel as per its frequency. There's no ambiguity then.

**Comment by sjperkins** [comment]
I remember the irregular spacing from our first discussions around this - I was wary of secondary index lookups in a GPU kernel and the compromise at that point was to resample the cube so that the spacings were regular.

I've thought about it a bit more tho. Can we assume a partial ordering on the lookup frequencies?

**Comment by o-smirnov** [comment]
You mean on the MS frequencies that we interpolate **to**? Yeah any given block of visibilities will have an ordered frequency axis.

**Comment by sjperkins** [comment]
Apologies I was using my phone for the previous comment.

> You mean on the MS frequencies that we interpolate to? 

I mean the "beam frequencies" mentioned in your comment yesterday.

> So you must store a vector of "beam frequencies", and interpolate each channel as per its frequency. There's no ambiguity then.

**Comment by o-smirnov** [comment]
The beam frequencies are also perfectly ordered.

**Comment by bennahugo** [comment]
@sjperkins @o-smirnov ... interestingly enough (but slightly off topic) I've been playing around with fitting Chebyshev polynomials per pixel to model the frequency dependence of a cube and I'm seeing pretty cool results. I'm able to compress a 1000 slice holography cube down to about 6 terms per pixel in the diagonal RR / LL terms and I recover most of the structure in the offdiagonal RL/LR terms with 18 terms per pixel.... although there is a bit more error involved with these. It may be worth investigating further...

**Comment by bennahugo** [comment]
Have an ipython notebook for this

**Comment by bennahugo** [comment]
https://github.com/bennahugo/algorithm_notebooks BeamInterpolator.ipynb

**Comment by sjperkins** [comment]
@bennahugo Cool stuff. As discussed earlier, I think this is a nice to have feature for Montblanc in future, but I'll have to think about how to fit the components along with everything else into kernel registers/shared memory.

I really like the idea!

**Comment by o-smirnov** [comment]
@bennahugo can you communicate this to @JulienNGirard and Kela? This is very relevant to their project...
