### ISSUE TITLE
Single channel  dimension disappears in resultant model_vis arrays in v5

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#152]
Sphe created a MeerKAT problem with a single channel. This caused the `_overwrite` function in `solve` to fall over on an assign statement due to a dimension mismatch.

Likely cause is the squeeze statement in `_enqueue_array_slice` or indexing instead of slicing

**Comment by sjperkins** [comment]
@marziarivi @SpheMakh I believe this is trivial to fix, I'll do so tomorrow morning.

**Comment by sjperkins** [comment]
Closed by #156 

@marziarivi  you may wish to cherry-pick the commit that fixed this into your branch (c49b6847e631f33ec63f34053c0775ba6e53440c) or rebase your branch ontop of master.

**Comment by marziarivi** [comment]
I updated my branch too.
Thanks,
Marzia
