### ISSUE TITLE
v2 E Beam expressions multiplies by wavelength instead of dividing

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#155]
Problem is [here](https://github.com/ska-sa/montblanc/blob/f7df35359d36de8ccdec4f0aa27494d13307bed4/montblanc/impl/rime/v2/gpu/RimeEK.py#L161).

Unless someone uses the beam expression in v2, this can probably be left standing until v2 is deprecated.

**Comment by marziarivi** [comment]
Actually it should multiply by c0/wavelength, i.e. frequency.

**Comment by sjperkins** [comment]
v2 is now deprecated
