### ISSUE TITLE
Allow custom data column for chi square computation

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/montblanc#159]
The current setup uses the DATA column to compute the chi square, and though the this can be manually changed by setting the `solver.observed_vis` array, it would more convenient to specify the data column when configuring the `montblanc.rime_solver` object

**Comment by sjperkins** [comment]
@SpheMakh Do you have a workaround for this at present?

**Comment by sjperkins** [comment]
# Implementation notes

Should make `INIT_WEIGHTS`  consistent with this somehow since they're both specifying where to obtain data from the MS. e.g.

- MS_OBSERVED_VISIBILITY_COLUMN
- MS_WEIGHT_COLUMN

or

- MS_OBSERVED_VISIBILITY_SOURCE
- MS_WEIGHT_SOURCE

**Comment by SpheMakh** [comment]
@sjperkins, I'll just simulate the data into the DATA column. This would more a convenience than a necessity.

**Comment by sjperkins** [comment]
Fixed in #185
