### ISSUE TITLE
Provide mechanism to supply SourceProvider data to SinkProviders

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#173]
SinkProviders may need access to the input for the particular chunk of the problem that was used to produce for e.g. a chunk of model visibilities.

For example when handling `model_vis` output its useful to have access to the `antenna1` and `antenna2` inputs to determine which baseline is being used.

/cc @JSKenyon

**Comment by JSKenyon** [comment]
Definitely - in general, I think that the antenna info is likely the most important. The time can be inferred, given that the data is assumed/forced to be correctly ordered in time. However, speaking from a calibration perspective, the baseline info is crucial.

**Comment by sjperkins** [comment]
Implemented in 253143ccb2662c74114e26300969cd0d97346bab, this can be closed when branch is merged.

**Comment by sjperkins** [comment]
Implemented in #185
