### ISSUE TITLE
cub md5sum mismatch when installing

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/montblanc#207]
I run into problems trying to install with 

$ pip install --log=mb.log git+git://github.com/ska-sa/montblanc.git@master 

Inspecting the log suggests there is a md5sum mismatch for the cub download:

Collecting git+git://github.com/ska-sa/montblanc.git@master
  Cloning git://github.com/ska-sa/montblanc.git (to master) to /tmp/pip-SlT0Ic-build
  Running command git clone -q git://github.com/ska-sa/montblanc.git /tmp/pip-SlT0Ic-build
  Running command git show-ref
  df2e50ccb695c74a3282ba4766a47f20cdfd0bbe refs/heads/master
  df2e50ccb695c74a3282ba4766a47f20cdfd0bbe refs/remotes/origin/HEAD
  5cef03e33a071afa3a412f003dfb147c5b7bce03 refs/remotes/origin/astropy-parallactic-angles
  7457d38869f01436afc5b23bbe674bdb8d98fd9c refs/remotes/origin/chi-simon
  a3b51fd3f38f0d354202c51ee19beb2f95e6391b refs/remotes/origin/chi_sqrd_gradient
  4ae177274e14287e3ae66235b40826d33f6e9c0c refs/remotes/origin/dask-tf-1.3
  4838dd927a49d282444ac2c01b8657d7404135d5 refs/remotes/origin/diag-g
  2f589f436e7f864caaa26937cbd2c3a40e84bdc3 refs/remotes/origin/dist-dask-tf
  47ce147185299009c7815dcc866d61207d9d0f4f refs/remotes/origin/dist-rime-tf
  77df76c70357c0ff525116ade8771a34176b94ae refs/remotes/origin/distributed-v6
  92b56f105f15dc5e9f7b3d3cc00cb9412af74556 refs/remotes/origin/kliko-integration
  df2e50ccb695c74a3282ba4766a47f20cdfd0bbe refs/remotes/origin/master
  7a3769dd0a0c192b9c013bbd7fbb181476a0eeab refs/remotes/origin/rime-tf
  90fe226c7f9b8601f3d9f0cc0e3d4f19b2d60d48 refs/remotes/origin/v5-debugging-example
  21be5cb54a4d1611e6c277c4024b2c80d6b85023 refs/tags/0.4.0-alpha2
  34d571e6ea626ac30fddce9d96201d939d51829f refs/tags/0.4.0-alpha3
  Running command git rev-parse HEAD
  df2e50ccb695c74a3282ba4766a47f20cdfd0bbe
  Running command git submodule update --init --recursive -q
  Running setup.py (path:/tmp/pip-SlT0Ic-build/setup.py) egg_info for package from git+git://github.com/ska-sa/montblanc.git@master
    Running command python setup.py egg_info
    Montblanc Install - WARNING - CUDA_PATH not found, inferring it as '/usr/local/cuda-8.0' from the nvcc location '/usr/local/cuda-8.0/bin/nvcc'
    nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    Montblanc Install - INFO - CUDA '8000' found. Installing tensorflow GPU
    Montblanc Install - INFO - CUDA installation settings:
    {
      "language": "c++",
      "define_macros": [],
      "nvcc_path": "/usr/local/cuda-8.0/bin/nvcc",
      "libraries": [
        "cudart",
        "cuda"
      ],
      "cuda_available": true,
      "library_dirs": [
        "/usr/local/cuda-8.0/lib64",
        "/usr/local/cuda-8.0/lib"
      ],
      "include_dirs": [
        "/usr/local/cuda-8.0/include"
      ]
    }
    Montblanc Install - INFO - CUDA code will be compiled for the following devices:
    [
      {
        "major": 3,
        "name": "GeForce GTX 870M",
        "minor": 0,
        "memory": 6368919552
      }
    ]
    Montblanc Install - INFO - No NVIDIA cub installation found
    Montblanc Install - INFO - Downloading cub archive 'https://github.com/NVlabs/cub/archive/1.6.4.zip'
    Montblanc Install - ERROR - NVIDIA cub install failed.
    Traceback (most recent call last):
      File "/tmp/pip-SlT0Ic-build/setup.py", line 105, in <module>
        install_cub(mb_inc_path)
      File "install/cub.py", line 140, in install_cub
        raise InstallCubException(msg)
    InstallCubException: Hash of file cub.zip downloaded from https://github.com/NVlabs/cub/archive/1.6.4.zip is 0d5659200132c2576be0b3959383fa756de6105d and does not match the expected hash of 7b669a049f05db811086d7774847cade6c88d1ec. Please manually download as per the README.md instructions.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-SlT0Ic-build/setup.py", line 105, in <module>
        install_cub(mb_inc_path)
      File "install/cub.py", line 140, in install_cub
        raise InstallCubException(msg)
    install.cub.InstallCubException: Hash of file cub.zip downloaded from https://github.com/NVlabs/cub/archive/1.6.4.zip is 0d5659200132c2576be0b3959383fa756de6105d and does not match the expected hash of 7b669a049f05db811086d7774847cade6c88d1ec. Please manually download as per the README.md instructions.
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-SlT0Ic-build/
Exception information:
Traceback (most recent call last):
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/landman/virtualenvs/mb_plus_cubi_env/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-SlT0Ic-build/

**Comment by sjperkins** [comment]
Fixed by #208
