### ISSUE TITLE
Make a release and use normal versions

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/montblanc#228]
please.

something like 0.5.0 or 0.4.1

http://semver.org/

**Comment by sjperkins** [comment]
I'll do a 0.5.0 release when I have space. Are you trying to package montblanc?

**Comment by gijzelaerr** [comment]
yes. 0.4.0 is in KERN-2, i would like to add a newer version to KERN-3.

**Comment by sjperkins** [comment]
Released [0.5.1](https://pypi.python.org/pypi/montblanc/0.5.1)

**Comment by gijzelaerr** [comment]
you are an amazing and wonderful person.

**Comment by sjperkins** [comment]
> you are an amazing and wonderful person.

Likewise the kernsuite stuff is really useful and a big time saver.

pip + setup.py struggles to build a local wheel for the pip cache, but I'm prepared to live with this for now.

**Comment by marziarivi** [comment]
What do you mean with normal version? Without tensor flow or without GPUs?
