### ISSUE TITLE
fixed dependency on python-casacore 2.1.2

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/montblanc#234]
Why is there a hard dependency on 2.1.2 in master? This causes problems with KERN-3 (as discussed with @JSKenyon on a related CubiCal thread).

**Comment by sjperkins** [comment]
I think there was a period where kern was on an old casacore but a new python-casacore and this caused breakage. I'll change this.

**Comment by sjperkins** [comment]
Fixed by #235
