### ISSUE TITLE
Montblanc needs native support for circular feeds

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/montblanc#237]
its a bit awkward needing to do further stokes conversions outside of the predictor, since it involves significant matrix multiplication to bring linear to circular (eq 17 Hamaker I). I'm not even sure it is correct to do it after applying E B G, etc. since that matrix belongs closest to the correlation matrix? @o-smirnov thoughts?

**Comment by bennahugo** [comment]
that matrix doesn't look like it will commute.

**Comment by sjperkins** [comment]
Montblanc supports circular feeds on master branch.
