### ISSUE TITLE
Montblanc predict significantly slower than Meqtrees

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/montblanc#241]
Single source in both cases:
Meqtrees takes under a minute to predict into a MeerKAT 16 100MHz dataset

1 iteration clean with predict in DDFacet + Montblanc (CPU):
montblanc predict..7665368/17609280 [=====================                             ]  43%  - 23'44"

**Comment by bennahugo** [comment]
(this is a 300MB dataset)

**Comment by sjperkins** [comment]
It's possible that's it's chosen some non optimal chunking strategy, but on the other hand, if I had a bitcoin for every time someone though Meqtrees war slower than Montblanc I'd be rich. I could throw together a benchmark when I return on Monday. Also see for example.

https://github.com/ratt-ru/CubiCal/issues/73
#issuecomment-338850781

and

https://github.com/ratt-ru/CubiCal/issues/81

Are you sure you haven't padded the data excessively? The progress bar suggests a lot of chunks for a 300MB dataset...

**Comment by sjperkins** [comment]
Have you set 'ntime' to the number of unique timesteps in the measurement set (not the total number of timesteps a.k.a. rows)

**Comment by bennahugo** [comment]
Unique timestamps - I just padded it nbl * ntime where nbl includes autocorrelations

**Comment by bennahugo** [comment]
I'll check again, but I really think this padding needs to be handled internally

**Comment by sjperkins** [comment]
@bennahugo it is, in the dask version.

**Comment by bennahugo** [comment]
Yup it is unique times - remember time centroid can shift around within an integration interval

After averaging down flagged data the centroid must be adjusted to be the correct timestamp of the data, which means very few baselines may share the exact same timestamp

**Comment by o-smirnov** [comment]
Looks like all we want for Christmas is the dask version of Montblanc...

**Comment by sjperkins** [comment]
@bennahugo can you reply with a URL pointing at your branch? I couldn't find it in amongst all the other DDFacet branches, or in your forked DDFacet-1 repo

**Comment by sjperkins** [comment]
Or just create a PR for it

**Comment by bennahugo** [comment]
It may actually be much faster to do the exponent based on uvw coordinates, not on the decomposition if it is the main reason why all baselines need to be present per slot? Alternatively the data needs to be regridded into common time bins before predicting?

**Comment by bennahugo** [comment]
@sjperkins  https://github.com/bennahugo/DDFacet/tree/fix-montblancpredict

**Comment by sjperkins** [comment]
@bennahugo there's a whole bunch of other design decisions here. Let's discuss this in person on Monday.

**Comment by sjperkins** [comment]
But I'm still suspicious of the calculation of  `self._ntime`. Check it against `len(np.unique(time))`

**Comment by sjperkins** [comment]
This a pathological case for the current master branch which will be solved in the dask version.
