### ISSUE TITLE
Addition of switches for various Jones terms

### ISSUE THREAD

**Issue by JSKenyon** [ska-sa/montblanc#245]
Currently, enabling and disabling individual Jones terms is very complicated. This is a particular problem for L Jones, as it is not always necessary. It can only be turned off by zeroing the parallactic angles. This, however, has repercussions for the E Jones term.

I think that it would be preferable to specify which Jones terms will enter into the RIME, rather than assuming all of them are present. This may have some impact on performance, but I do feel it is crucial if the intention is to support simulation in general.

**Comment by sjperkins** [comment]
Thanks for digging into this, I can see why this is a problem. I'll try look into it next week.

Related to https://github.com/ska-sa/montblanc/issues/168

**Comment by sjperkins** [comment]
Closed in favour of #254
