### ISSUE TITLE
numba caching failing: cannot cache function 'isclose': no locator available

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/montblanc#253]
I'm getting this error with on master branch
```
cannot cache function 'isclose': no locator available for file '/usr/local/lib/python2.7/dist-packages/montblanc/util/ant_uvw.py'
```
 I think its related to this https://stackoverflow.com/questions/44183779/numba-caching-issue-cannot-cache-function-no-locator-available-for-file

**Comment by sjperkins** [comment]
Yep, numba caches compiled functions in a `__pycache__` directory. Is this installed as a user, or running in some directory where no write permissions are available?

**Comment by SpheMakh** [comment]
It /usr/lib, but the user is not root. Installing in a virtualenv should fix this right?

**Comment by sjperkins** [comment]
Yes, a virtualenv should fix this. Alternatively, you could try setting `NUMBA_CACHE_DIR` as suggested by https://stackoverflow.com/questions/44183779/numba-caching-issue-cannot-cache-function-no-locator-available-for-file#comment75382183_44183779

**Comment by SpheMakh** [comment]
Sorted

**Comment by arose13** [comment]
Does this mean you cannot fun numba on distributed computing systems? (with spark etc)
