### ISSUE TITLE
Missing symbols in anaconda tensorflow binaries cause RIME custom operators to fail.

### ISSUE THREAD

**Issue by vafaei-ar** [ska-sa/montblanc#258]
I've installed the package successfully on Geneva cluster, but it gets below error when I've tried to tun standalone.py:

tensorflow.python.framework.errors_impl.NotFoundError: /home/vafaeisa/anaconda2/lib/python2.7/site-packages/montblanc-0.5.1+11.ge29c6ef-py2.7-linux-x86_64.egg/montblanc/ext/rime.so: undefined symbol: _ZN10tensorflow15shape_inference16InferenceContext11DebugStringENS0_11ShapeHandleE

**Comment by sjperkins** [comment]
The anaconda tensorflow binaries seem to be missing the above symbol (perhaps amongst others) which causes linking problems with Montblanc's custom operators.

@vafaei-ar pip installed the pypi version of tensorflow (within anaconda) and this seems to solve the problem.
