### ISSUE TITLE
Provide a SharedData member that provides a count of the Weighted Visibility Components

### ISSUE THREAD

**Issue by jtlz2** [ska-sa/montblanc#39]
@sjperkins At the moment we calculate the number of visibilities as

    ndata=8*sd.nbl*sd.nchan*sd.ntime

But some of these will be flagged and hence ignorable in the summation. Are you able to provide a sd.ndata attribute that is essentially a counter of the actual number of unflagged visibilities used in the summation? Low-weight visibilities - or anything else used in the summation - should still count.

**Comment by sjperkins** [comment]
Implemented in abd542a18eca211d69e211fe4f2f9120317840c3.
