### ISSUE TITLE
Need to implement a G-Jones kernel

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/montblanc#52]
Direction-independent term: dimension is 4 x Nfreq x Ntime x Nantenna. 

A possible optimization is to support a scalar Jones term (1 x Nfreq x Ntime x Nantenna).

**Comment by sjperkins** [comment]
Implemented in a477514452aa5fa8e1fca75657b05ab6760b1f25 and b1eff8d4072d0c33aca00cd97d3708094b13f1db.
