### ISSUE TITLE
if released I make a package

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/montblanc#71]
and add it to the radio astro PPA.

**Comment by sjperkins** [comment]
@gijzelaerr I'm open to the idea. What do you need from me to do this?

**Comment by gijzelaerr** [comment]
Assuming you want to keep things simple and just do releases from your master branch, just press the release button on github :)

https://github.com/ska-sa/montblanc/releases/new

Maks sure all versions match up in your `setup.py` file. Thats it.

**Comment by sjperkins** [comment]
@gijzelaerr I've added a v0.4.0-alpha1 tag, so 0.4.0-alpha1 is the first release. Close this issue if you're happy with that?

**Comment by sjperkins** [comment]
Created first release https://github.com/ska-sa/montblanc/releases/tag/v0.4.0-alpha1.
