### ISSUE TITLE
alpha2 package is numbered as alpha1 and is manipulated during build

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/montblanc#74]
montblanc/version.py in the  alpha2 tarball contain:
```
__version__=v0.4.0-alpha1
```

After a `python setup.py build` the file contains:
```
__version__='v0.4.0-alpha1'
```

**Comment by sjperkins** [comment]
Fixed by 21be5cb54a4d1611e6c277c4024b2c80d6b85023. Retagged 0.4.0-alpha2 release with this commit.
