### ISSUE TITLE
integer conversion resulted in a change of sign

### ISSUE THREAD

**Issue by jtlz2** [ska-sa/montblanc#88]
@sjperkins I think this is a known issue/wontfix - it's not really a problem, right?

The CUDA compiler succeeded, but said the following:
/home/bhengu/montblanc/montblanc/src/montblanc/include/jones.cuh(60): warning: integer conversion resulted in a change of sign
          detected during instantiation of "void rime_jones_EKBSqrt_impl(EKBTraits<T>::UVWType *, EKBTraits<T>::LMType *, T *, Tr::ct *, Tr::ct *) [with T=float, Tr=montblanc::kernel_traits<float>, Po=montblanc::kernel_policies<float>]"
kernel.cu 
(123): here

/home/bhengu/montblanc/montblanc/src/montblanc/include/jones.cuh(60): warning: integer conversion resulted in a change of sign

/home/bhengu/montblanc/montblanc/src/montblanc/include/jones.cuh(101): warning: integer conversion resulted in a change of sign

he CUDA compiler succeeded, but said the following:
/home/bhengu/montblanc/montblanc/src/montblanc/include/jones.cuh(101): warning: integer conversion resulted in a change of sign
          detected during instantiation of "void rime_sum_coherencies_impl<T,apply_weights,Tr,Po>(SumCohTraits<T>::UVWType *, Tr::ft *, Tr::ft *, Tr::ft *, int *, Tr::ct *, Tr::ft *, Tr::ct *, Tr::ct *, Tr::ct *, Tr::ft *) [with T=float, apply_weights=false, Tr=montblanc::kernel_traits<float>, Po=montblanc::kernel_policies<float>]"
kernel.cu 
(288): here

/home/bhengu/montblanc/montblanc/src/montblanc/include/jones.cuh(60): warning: integer conversion resulted in a change of sign

/home/bhengu/montblanc/montblanc/src/montblanc/include/jones.cuh(101): warning: integer conversion resulted in a change of sign

**Comment by sjperkins** [comment]
@jtlz2 Yes, lets keep the issue, buts its very low priority for me at present.

**Comment by sjperkins** [comment]
Fixed by #123.
