### ISSUE TITLE
Dockerise Montblanc

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/montblanc#95]
- Put montblanc in a docker container.
- Needs CUDA 7.5.
- Take a look at https://github.com/NVIDIA/nvidia-docker.

**Comment by sjperkins** [comment]
@gijzelaerr See [this](https://github.com/ska-sa/montblanc/commits/kliko-integration) branch and [this](https://github.com/ska-sa/montblanc/commit/54ceceab271d78e744951646d08305a425c1819c) commit.

**Comment by gijzelaerr** [comment]
also see this docker file https://github.com/ska-sa/montblanc/commit/488d4ca9dcf8dcfcfc4ee99e9d014ea9f8a0d38f

which should install montblanc in a CUDA container. last thing we need is:
* an entrypoint script
* a wrapper to confirm to the Kliko standard

**Comment by sjperkins** [comment]
Entrypoint script `docker/entrypoint.py` added in 54ceceab271d78e744951646d08305a425c1819c.

**Comment by gijzelaerr** [comment]
montblanc is now a debian package in KERN:
https://github.com/kernsuite-debian/montblanc

which makes it trivial to create a docker container using the KERN suite base container.
